# Generated by Django 5.2.4 on 2025-08-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_post_postvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default=0, upload_to='project_videos'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostVideo',
        ),
    ]
