# Generated by Django 5.2.4 on 2025-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
