# Generated by Django 5.2.4 on 2025-08-22 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userprofile_first_name_userprofile_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='project',
        ),
        migrations.RenameModel(
            old_name='post_reply',
            new_name='project_reply',
        ),
    ]
